let lyrics = `
I'm a survivor, I'm a survivor

I don't know how to trust myself
It's like I turned to someone else
But I can't let the dark consume me
Let the light shine right through me
It's feeling like the air's gone stale
And all the wind's out my sails
But I can't let the dark consume me
Consume me

I feel it in my soul
No, I won't go, I won't go
Through highs and all the lows
I'm a survivor, I'm a survivor
I feel it in my soul
No, I won't fold, I won't fold
My river always flows, oh
I'm a survivor, I'm a survivor

I'm a survivor, I'm a survivor

You might also like
FACTS
Tom MacDonald
Selfish
Justin Timberlake
Big Foot
Nicki Minaj

I feel the the weight keep bearing down
As I'm reaching for higher ground
Yeah, I won't let these mountains phase me
With every step I'm elevating
I hear the vultures call my name
But I'm not going in my grave
Yeah, I'ma be the one who saves me
Who saves me

I feel it in my soul
No, I won't go, I won't go
Through highs and all the lows
I'm a survivor, I'm a survivor
I feel it in my soul
No, I won't fold, I won't fold
My river always flows, oh
I'm a survivor, I'm a survivor

I'm a survivor
I'm a survivor-vivor-vivor
I'm as surv—
I'm a surv—
I'm a survivor
I'm a survi-v-vivor-vivor

I'm a survivor
I feel it in my soul
No, I won't go, I won't go
Through highs and all the lows
I'm a survivor, I'm a survivor

I feel it in my soul
No, I won't fold, I won't fold
My river always flows, oh
I'm a survivor, I'm a survivor

I'm a survivor, I'm a survivor
I'm a survivor, I'm a survivor
I'm a survivor, I'm a survivor
I'm a survivor
`;

document.getElementById('Lyrics').innerHTML = lyrics;